site_name: MyNotes
theme: readthedocs
nav:
  - Home: index.md
  - ITPMP:
    - 项目管理概论: ITPMP/项目管理概论.md
    - 项目立项管理: ITPMP/项目立项管理.md
    - 项目整合管理: ITPMP/项目整合管理.md
    - 项目范围管理: ITPMP/项目范围管理.md
    - 项目范围管理-重点: ITPMP/项目范围管理-重点.md
    - 项目进度管理: ITPMP/项目进度管理.md
    - 项目成本管理: ITPMP/项目成本管理.md
    - 项目质量管理: ITPMP/项目质量管理.md
    - 项目资源管理: ITPMP/项目资源管理.md
    - 项目沟通管理: ITPMP/项目沟通管理.md
    - 项目风险管理: ITPMP/项目风险管理.md
    - 项目采购管理: ITPMP/项目采购管理.md
    - 项目干系人管理: ITPMP/项目干系人管理.md
    - 项目绩效域: ITPMP/项目绩效域.md
    - 配置和变更管理: ITPMP/配置和变更管理.md
    - 高级项目管理: ITPMP/高级项目管理.md
    - 管理学科知识: ITPMP/管理学科知识.md
    - 组织通用治理: ITPMP/组织通用治理.md
    - 组织通用管理: ITPMP/组织通用管理.md
